Added cpu interrupts, softirqs, softnet-stat
sensu-plugins/sensu-plugins-cpu-checks pull request #33
Opened 2018-04-09 11:51 UTC by yuri-zubov

## Pull Request Checklist

**Is this in reference to an existing issue?**

#### General

- [ ] Update Changelog following the conventions laid out [here](https://github.com/sensu-plugins/community/blob/master/HOW_WE_CHANGELOG.md)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [ ] RuboCop passes

- [ ] Existing tests pass

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

#### Purpose

#### Known Compatibility Issues

2018-04-18 01:24 UTC, majormoses requested changes
Overall I think it looks good but has some unintentional breaking changes.

2018-04-18 01:24 UTC, majormoses commented on bin/metrics-cpu-pcnt-usage.rb
> +      if name.match?(/^cpu$/)
`.match?` was added in ruby 2.4

2018-04-18 01:24 UTC, majormoses commented on bin/metrics-cpu.rb
> +      if name.match?(/cpu([0-9]+|)/)
`.match?` was added in ruby 2.4

2018-04-18 11:02 UTC, yuri-zubov commented
@majormoses - fixed. Recheck, please

2018-04-19 05:16 UTC, majormoses approved these changes

2018-04-19 05:16 UTC, merged

2018-04-19 05:26 UTC, majormoses commented
released: https://rubygems.org/gems/sensu-plugins-cpu-checks/versions/2.1.0